# Generated by Django 3.2.14 on 2022-07-11 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire', '0002_remove_questionaire_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionaire',
            old_name='first_name',
            new_name='name',
        ),
    ]
